### ISSUE TITLE
setInterval

### ISSUE THREAD

**Issue by katoto** [AEPKILL/devtools-detector#1]
setInterval ? 你用500 一直查询？

**Comment by AEPKILL** [comment]
用的 `setTimeout` 做循环检测，`setTimeout` 比 `setInterval` 更容易控制。
因为浏览器并没有提供 `devtools` 打开时的事件，所以必须循环检测。
其实用 `requestIdleCallback` 方法可以获取最优的性能，但是 `IE` 浏览器并不支持这个方法。
