### ISSUE TITLE
lanuch still exists

### ISSUE THREAD

**Issue by huanshiwushuang** [AEPKILL/devtools-detector#10]
I saw your submission record [lanuch --> launch].
But I still can only start via devtoolsDetector.lanuch(), not devtoolsDetector.launch().
I can still search for the lanuch keyword in the build code.
Is this correct?【from google translate】

**Comment by AEPKILL** [comment]
Try upgrading to v1.0.22.

Still retain `lanuch` method, because remove `lanuch ` is a breaking change.
