### ISSUE TITLE
why count === 2 is not count === 1 in function-to-string.checker ?

### ISSUE THREAD

**Issue by claviering** [AEPKILL/devtools-detector#28]
https://github.com/AEPKILL/devtools-detector/blob/1781eb8c94b2a00e830376472bce7c02178c2831/src/checkers/function-to-string.checker.ts#L27

**Comment by AEPKILL** [comment]
because `toSting` method will be invoked twice.

**Comment by claviering** [comment]
> because `toSting` method will be invoked twice.

I try to only using `devtoolsTestFunction.toString `, `toString `method will be invoked once. Where be invoked another once?
