### ISSUE TITLE
Not working on Firefox

### ISSUE THREAD

**Issue by cherrad** [AEPKILL/devtools-detector#31]
The demo and from localhost are not detecting DevTools when opened on firefox always "Close"
The console says that it can not load the javascript but the file is reachable.
Tested also on Google Chrome, Opera GX and Ms Edge and it works fine.
![devtools-detector demo — Mozilla Firefox 2021-10-15 09_43_11](https://user-images.githubusercontent.com/37696143/137459153-4b734ed6-520d-4a24-ac33-150d36919f12.png)
 - 
![devtools-detector demo — Mozilla Firefox 2021-10-15 09_44_07](https://user-images.githubusercontent.com/37696143/137459250-be5b332f-0a85-4e7f-88cb-ab932a4451df.png)

**Comment by AEPKILL** [comment]
I will fix it within this week
