### ISSUE TITLE
script causes issues with google indexing

### ISSUE THREAD

**Issue by shorts7wound** [AEPKILL/devtools-detector#33]
hello it seems that when script is added in the page google cannot index the page and shows error

**Comment by AEPKILL** [comment]
sorry, i don't know how to use google index

**Comment by shorts7wound** [comment]
itsomehow interfers with google trying to render the page so i added this code checking if useragent contains the word bot
if(!(strstr(strtolower($_SERVER['HTTP_USER_AGENT']), "bot")) || (strstr(strtolower($_SERVER['HTTP_USER_AGENT']), "crawl"))  || (strstr(strtolower($_SERVER['HTTP_USER_AGENT']), "slurp"))  || (strstr(strtolower($_SERVER['HTTP_USER_AGENT']), "spider"))  || (strstr(strtolower($_SERVER['HTTP_USER_AGENT']), "mediapartners"))   )
