### ISSUE TITLE
将Tencent/vConsole置于devtools-detector前加载会导致判断失效

### ISSUE THREAD

**Issue by BecodReyes** [AEPKILL/devtools-detector#35]
在DEMO中测试成功 (拉到本地方便插入，除此之外无修改)
将[Tencent/vConsole](https://github.com/Tencent/vConsole)置于devtools-detector前加载会导致判断失效
![](https://inews.gtimg.com/newsapp_ls/0/14418922345/0)
感觉应该无解

**Comment by AEPKILL** [comment]
你要保证 devtools-detector 在所有代码之前加载。

这个也可以解决，只要创建一个纯净的运行环境就好了，比如：

```
var iframe = document.createElement('iframe')
iframe.src = 'about::blank';
iframe.style.display = 'none';
document.body.append(iframe);

iframe.contentWindow.window.console.log( ..... )
```

但是没必要，因为这个库是你自己主动引入的，你是有能力控制代码的加载顺序的。

**Comment by BecodReyes** [comment]
引用该库主要是为了防止模板被扒
个人测试即使是放在最前也是可以使用fiddler给修改掉的
不过放在iframe里的确是个不错的点子
谢谢你的回复

**Comment by AEPKILL** [comment]
这个本来就是防君子不防小人的，要想完全隐藏自己的代码可以尝试借助 WebAssembly 或者像 google recaptcha 一样实现一个自己的 vm
