### ISSUE TITLE
Chrome 102 Error

### ISSUE THREAD

**Issue by francotc** [AEPKILL/devtools-detector#38]
![image](https://user-images.githubusercontent.com/15241240/170124134-f3f3fcd8-dc0f-4e78-a4ee-c58490447677.png)
![image](https://user-images.githubusercontent.com/15241240/170124215-6acdef63-c059-430e-8eaa-3001a816d9be.png)
New chrome version throw error on debugger

**Comment by AEPKILL** [comment]
I added a way to detect，please try the latest demo: [DEMO](https://blog.aepkill.com/demos/devtools-detector/)
But I don't have a lot of testing, so I didn't publish to npm

**Comment by francotc** [comment]
It seems to work now as its should be, great

**Comment by thkim2015** [comment]
New [DEMO](https://blog.aepkill.com/demos/devtools-detector/) does not work in Firefox, while the previous not-fixed version does well.

![image](https://user-images.githubusercontent.com/10259108/172997220-08cbd7a9-77c5-4a37-a236-77d26a9ca2f2.png)

**Comment by francotc** [comment]
Chrome 104 throw same error
