### ISSUE TITLE
google 版本 72.0.3626.121（正式版本） （64 位）不支持

### ISSUE THREAD

**Issue by guoxiaobei** [AEPKILL/devtools-detector#4]
支持各个浏览器到什么版本 试了一下谷歌版本 72.0.3626.121（正式版本） （64 位）不支持

**Comment by AEPKILL** [comment]
呃 是支持的 我忘了更新 demo 了

**Comment by guoxiaobei** [comment]
![image](https://user-images.githubusercontent.com/26620613/53854560-e0f96b80-4004-11e9-83c1-da29fb1a9761.png)

**Comment by guoxiaobei** [comment]
![image](https://user-images.githubusercontent.com/26620613/53854671-59602c80-4005-11e9-9f50-ec3c73927bbd.png)

**Comment by AEPKILL** [comment]
我看你的截图是没有问题的啊

**Comment by guoxiaobei** [comment]
![image](https://user-images.githubusercontent.com/26620613/53858604-d3001680-4015-11e9-81d5-0f9ac09bd246.png)
y应该是这种的呀

**Comment by AEPKILL** [comment]
> ![image](https://user-images.githubusercontent.com/26620613/53858604-d3001680-4015-11e9-81d5-0f9ac09bd246.png)
> 应该是这种的呀

这个只是其中的一种检测方式

`devtools-detector` 内置了好多种检测方式，在这里查看到所有检查策略: [checkers](https://github.com/AEPKILL/devtools-detector/tree/master/src/devtools-checker)


只要你打开控制台页面上的文字会变成: 'devtools status: open'
关闭控制台页面上的文字会变成: 'devtools status: close'
那么久说明是检测成功的。

如果你只需要这一种检测策略要可以这么写:
```typescript
import { Detector, debuggerChecker } from 'devtools-detector';

const detector = new Detector({ checkers: [debuggerChecker] });
const view = document.createElement('div');

document.body.appendChild(view);

detector.addListener(
  isOpen =>
    (view.innerText = isOpen
      ? 'devtools status: open'
      : 'devtools status: close')
);

detector.lanuch();
```

建议你使用默认的检测策略
