### ISSUE TITLE
Updated version does not work in Firefox

### ISSUE THREAD

**Issue by thkim2015** [AEPKILL/devtools-detector#40]
New [DEMO](https://blog.aepkill.com/demos/devtools-detector/) shows always 'open' status in Firefox, while the previous version before the closed issue #38, works prefectly well.

![image](https://user-images.githubusercontent.com/10259108/172997220-08cbd7a9-77c5-4a37-a236-77d26a9ca2f2.png)

**Comment by AEPKILL** [comment]
fixed.
