### ISSUE TITLE
Performance checker 频繁误触发 isOpen

### ISSUE THREAD

**Issue by partyspy** [AEPKILL/devtools-detector#42]
Windows, MacOS, iPhone 设备皆有

**Comment by partyspy** [comment]
看似触发的阈值有点问题？

https://user-images.githubusercontent.com/5229368/176423138-55f87965-90ef-46b8-9478-753da91a00df.MOV

**Comment by ltinerary** [comment]
后面是怎么解决的？我也是遇到这个类似的问题了 #48
