### ISSUE TITLE
activate performance checker only on prod build

### ISSUE THREAD

**Issue by mirobo** [AEPKILL/devtools-detector#44]
hey there

is it possible to NOT log "largeObject" to the console when the performance checker is just imported? When I import "performanceChecker" the code gets executed immediately and slows down execution of various tests...

```
const largeObject = createLargeObject();
const largeObjectArray: Record<string, string>[] = [];

for (let i = 0; i < 50; i++) {
  largeObjectArray.push(largeObject);
}
```

thanks!
miro

**Comment by AEPKILL** [comment]
It's lazy initialization now

**Comment by mirobo** [comment]
> It's lazy initialization now

thank you so much, I'll try it out :-D
