### ISSUE TITLE
Disable console clearing

### ISSUE THREAD

**Issue by Valar353** [AEPKILL/devtools-detector#46]
Hey! Is it possible to disable console clearing?

**Comment by AEPKILL** [comment]
If clear is disabled, a lot of information for detection will appear in the console (every detection loop)
If you want the your debugging information not to cleared, you can turn off the detection in the development environment

```ts
if (!__DEV__) {  devtoolsDetector.launch() }
```

**Comment by Valar353** [comment]
Got it, thanks for the reply. However, the library clears the console before I call the `launch` method, is there any way to get around this?

**Comment by AEPKILL** [comment]
I just tried it won't clear the console before call the `launch` method

**Comment by AEPKILL** [comment]
> I am using a package which uses devtoolsDetector (@d-i-t-a/reader) and so I do not have control over devtoolsDetector.launch() nor do I see that anywhere in the reader code. Is there another way to configure devtools-detector not to clear the console?

you can rewrite `devtoolsDetector.launch` method before import `@d-i-t-a/reader`

e.g.

```ts

devtoolsDetector.launch = () => void

const reader = require("@d-i-t-a/reader")

```

**Comment by jdempcy** [comment]
This disables other functionality used by the module for its content protection which requires detecting when the dev tools are open. What I really need to do is disable the console clearing. I actually found a way to do this by just pointing console.clear to an empty function, ilke you did with the launch method. In the index.html for the whole React app I simply add a script like so:

``` 
<!-- Disable console.clear() for debugging purposes -->
<script type="text/javascript">console.clear = () => void;</script>
```

Thanks for the great tool! And for the good idea of overriding the method like that :)

**Comment by jdempcy** [comment]
> Hey! Is it possible to disable console clearing?

@Valar353 You can do this by overriding console.clear().

**Comment by jdempcy** [comment]
@AEPKILL  this question can be closed as there is a suitable workaround (imo)

**Comment by jdempcy** [comment]
Note that pointing to void did not work for me and I actually had to override to an empty function with () => {}.

**Comment by jfaylon** [comment]
I'm trying to override the console.clear but to no avail. Is there a way to disable the logs for this module instead of clearing as this affects globally?
