### ISSUE TITLE
仅部分页面需要检测是否允许开启控制台的场景，第一次进入会做检测，重复进入无法检测

### ISSUE THREAD

**Issue by xsTao** [AEPKILL/devtools-detector#58]
第一次进入页面会进addLisener, 不刷新页面再进入就不会再进addListener。
addLisener 和 launch 是在该页面运行的，请问这种场景是否支持？

chrome: 85.0.4183.102（正式版本） （64 位）

**Comment by AEPKILL** [comment]
addListener 仅在状态变更时触发
