### ISSUE TITLE
为什么demo有debugger，而我用了npm库，没有这个功能？

### ISSUE THREAD

**Issue by pxim** [AEPKILL/devtools-detector#62]
![image](https://user-images.githubusercontent.com/5111701/225808673-3239e345-0798-454d-a997-0fb25345e2f7.png)

这是我的代码
![image](https://user-images.githubusercontent.com/5111701/225808716-4d940d4a-fc9f-41d6-be2b-0bf1a8a55c45.png)

**Comment by AEPKILL** [comment]
打开 Devtools 刷新页面就会触发 debugger
