### ISSUE TITLE
Would you please help me to create a tag for 2.0.14?

### ISSUE THREAD

**Issue by dolinyuan** [AEPKILL/devtools-detector#66]
Hello creator, this tool is really amazing. And I used it in my project and received high recognition. Thank you very much for sharing it. Now, I hope to stabilize version 2.0.14 in the project, please be kind to create a tag for it, thank you in advance~

**Comment by AEPKILL** [comment]
I apologize for taking so long to reply to you. I have been busy with some other matters. I have created a tag for 2.0.14, but I still recommend using `npm` to manage dependencies and versions.

**Comment by dolinyuan** [comment]
Hi, dear, words cannot express how thankful I am, and please accept my heartfelt thanks for your kind and warm help ～



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 17, 2023 18:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [AEPKILL/devtools-detector] Would you please help me to create atag for 2.0.14? (Issue #66)




 
I apologize for taking so long to reply to you. I have been busy with some other matters. I have created a tag for 2.0.14, but I still recommend using npm to manage dependencies and versions.
