### ISSUE TITLE
inquiry

### ISSUE THREAD

**Issue by zhang-glitch** [AEPKILL/devtools-detector#68]
Hello, author. At present, it is not only effective to monitor the width and height of the visual area and check the performance by printing. Nothing else works, okay?

**Comment by AEPKILL** [comment]
Are you want only enabling performance and viewport checks to verify if devtools is open?

See #64 

By the way, viewport checks have been deprecated because they lead to erroneous judgments in many edge cases.

**Comment by zhang-glitch** [comment]
作者，我的意思是目前除了监听视口宽高，debugger, 打印监听性能这三种方式，其他方式对于chrome来说都不适用了吗？

**Comment by AEPKILL** [comment]
> 作者，我的意思是目前除了监听视口宽高，debugger, 打印监听性能这三种方式，其他方式对于chrome来说都不适用了吗？

是的。

对于反调试而言这些检查方式都可以绕过的，只是稍微增加了一点点难度。
