### ISSUE TITLE
launch() doesnt work if we navigate keeping the developer tools already open

### ISSUE THREAD

**Issue by mohiyuddinshaikh** [AEPKILL/devtools-detector#69]
The library works perfectly when you open the devtools.
But say in my react app, i am on page A where devtools is allowed. So devtools is open.
I then navigate to page B where devtools is not allowed and where I am using the library, but this time it doesnt detect that devtools was already open and hence user can access dev tools where I dont want them to.

**Comment by AEPKILL** [comment]
You need to remember the previous status of devtools because the message won't trigger unless devtools' status has changed.

```ts
import { useEffect, useState } from "react";
import {
  launch,
  stop,
  isLaunch,
  addListener,
  removeListener,
  DevtoolsDetail,
  DevtoolsDetectorListener,
} from "devtools-detector";

let devtoolsIsOpened = false;
export function useDevtoolsIsOpen() {
  const [isOpen, setIsOpen] = useState(devtoolsIsOpened);

  useEffect(() => {
    if (isLaunch()) return;

    const devtoolsListener: DevtoolsDetectorListener = (isOpen) => {
      devtoolsIsOpened = isOpen;
      setIsOpen(isOpen);
    };

    addListener(devtoolsListener);
    launch();
    return () => {
      removeListener(devtoolsListener);
      stop();
    };
  }, []);

  return isOpen;
}

```

[Example](https://codesandbox.io/p/sandbox/devtools-detector-launch-92hzrn)
