### ISSUE TITLE
Ios edge browser recognizes developer tool

### ISSUE THREAD

**Issue by youdk1107** [AEPKILL/devtools-detector#74]
There is a problem with recognizing that the developer tool has been opened even if the developer tool is not opened in the iOS edge browser.

I have added an alert code to verify.
![capture](https://github.com/user-attachments/assets/799b7b01-662f-4af3-a205-8b67dc93bb08)

The ios edge version is 127.2651.96.
![capture2](https://github.com/user-attachments/assets/eefa8167-8be5-49c5-84dd-0a0f67097ed1)

**Comment by AEPKILL** [comment]
Fixed, but I don't have an iOS device to test it. If there are any problems, please reopen this issue.

**Comment by youdk1107** [comment]
The error has not been resolved.

It seems that edge recognition is not possible because the value for distinguishing edge by useragent on iOS is EdgiOS.

If you modify the edge confirmation condition as below, it was recognized as normal.

/** edge */
export const isEdge = /edge/i.test(userAgent) ||
                      /EdgiOS/i.test(userAgent);



The regToStringChecker function also seems to be detect regardless of developer tool usage in iOS edge browser.

There was no problem with other browsers, and only iOS edge browsers were experiencing problems.

**Comment by youdk1107** [comment]
The regToStringChecker function also seems to be detect regardless of developer tool usage in iOS edge browser.

As long as you modify the regToStringChecker function, it worked fine on iOS as well.

**Comment by AEPKILL** [comment]
> The regToStringChecker function also seems to be detect regardless of developer tool usage in iOS edge browser.
> 
> As long as you modify the regToStringChecker function, it worked fine on iOS as well.

It was also fixed in the last modification.

https://github.com/AEPKILL/devtools-detector/blob/00a2d3e6cdedbefd113cb2cc0326bbbbd5796c81/src/checkers/reg-to-string.checker.ts#L29
