### ISSUE TITLE
False detection when devtool is not opened

### ISSUE THREAD

**Issue by vijay16081998** [AEPKILL/devtools-detector#75]
Hii.
     Thanks for sharing this devtool detector library file.
    
     When using your latest version 2.0.22 javascript, dev tool detector code in my application, randomly after using 2 minutes facing devtool open issue even though devtool is not opened. (False detection even dev tool not opened)

      Can you tell me the solution how to fix and 
Resolve this issue?

**Comment by AEPKILL** [comment]
Could you provide a minimal reproducible demo of the issue?
